#!/bin/bash

NORMAL="\\033[0;39m"
SUCCESS="\\033[1;32m"
INFO="\\033[1;36m"

zprint() {
    echo -e "[${INFO} ${1} ${INFO}${NORMAL}]"
}

zmountfs() {
    zprint "Mount filesystem"
    mount --options remount,rw / > /dev/null
    mkdir -p /dev/pts
    mount --all --test-opts no_netdev > /dev/null

}

zmountvfs() {
    zprint "Mount virtual filesystem"
    if ! mountpoint /run >/dev/null; then
       mount /run
    fi

    mkdir -p /run/lock /run/shm
    chmod 1777 /run/shm /run/lock

    if ! mountpoint /proc >/dev/null; then
       mount -o nosuid,noexec,nodev /proc
    fi

    if ! mountpoint /sys >/dev/null; then
       mount -o nosuid,noexec,nodev /sys
    fi

    if ! mountpoint /dev >/dev/null; then
       mount -o mode=0755,nosuid /dev
    fi
    ln -sfn /run/shm /dev/shm
}

zcheckfs() {
    zprint "Check fs"
    mount -n -o remount,ro / >/dev/null
    fsck  -a -A -C -T
}

start_udev() {
    zprint "Start udev"
    /sbin/udevd --daemon
    /sbin/udevadm trigger --action=add    --type=subsystems
    /sbin/udevadm trigger --action=add    --type=devices
    /sbin/udevadm trigger --action=change --type=devices
    /sbin/udevadm settle
}

zstart_swap() {
    zprint "Start swap"
	swapon -a
}

zset_hostname() {
    zprint "Set hostname"
    [ -r /etc/hostname ] && HOSTNAME=`cat /etc/hostname`
    hostname ${HOSTNAME}
}

znetwork_setup() {
    zprint "Network setup"

    ip addr add 127.0.0.1/8 label lo dev lo
    ip link set lo up

    CARD="enp0s25"
    IP="192.168.2.21/24"
    GATEWAY="192.168.2.1"
    ip link set ${CARD} up
    ip addr add ${IP} dev ${CARD}
    ip route add default  via ${GATEWAY} dev ${CARD}

}

zstart_sshd() {
    zprint "Start sshd"
    /usr/sbin/sshd
}

zumountfs() {
    zprint "Umount all filesystem"
    losetup -D
    umount --all --detach-loop --read-only \
    --types notmpfs,nosysfs,nodevtmpfs,noproc,nodevpts >/dev/null
    mount --options remount,ro /

}

zstop_network() {
    zprint "Stop network"
    CARD="enp0s25"
    ip link set lo down
    ip link set ${CARD} down
}

zstop_swap() {
    zprint "Stop swap"
    swapoff -a
}

zstart_dbus() {
    zprint "Start dbus"
    mkdir -p /run/dbus
    /usr/bin/dbus-uuidgen --ensure
    /usr/bin/dbus-daemon --system
}

zstart() {
    zmountvfs
    start_udev
    zcheckfs
    zmountfs
    zstart_swap
    zset_hostname
    znetwork_setup
    zstart_sshd
    zstart_dbus
}

zstop() {
    zumountfs
    zstop_network
    zstop_swap
}

case ${1} in
    start)
        zprint "Start"
        zstart
        ;;
    stop)
    	zprint "Stop"
        zstop
    	halt -d -f -i -p
        ;;
    reboot)
    	zprint "Reboot"
        zstop
    	reboot -d -f -i
        ;;
    *)
        echo "Usage: ${0} {start|stop|reboot}"
        exit 1
esac
